# Generated by Django 5.0.6 on 2024-12-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_articles_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="autor",
            field=models.CharField(
                default="admin", max_length=50, verbose_name="Автор"
            ),
        ),
        migrations.AlterField(
            model_name="articles",
            name="anons",
            field=models.CharField(
                default="Дэфолт анонс", max_length=50, verbose_name="Анонс"
            ),
        ),
        migrations.AlterField(
            model_name="articles",
            name="full_text",
            field=models.TextField(
                default="Дэфолт что-то интересное",
                max_length=250,
                verbose_name="Статья",
            ),
        ),
    ]
