# Generated by Django 5.0.6 on 2024-12-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_articles_autor_alter_articles_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articles",
            name="autor",
            field=models.CharField(max_length=50, verbose_name="Автор"),
        ),
    ]
